DROP TABLE SHOPS CASCADE CONSTRAINTS;
DROP TABLE ITEMS CASCADE CONSTRAINTS;
DROP TABLE SUPPLIERS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE SHOP_ITEMS CASCADE CONSTRAINTS;
DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE SUPPLIER_ITEMS CASCADE CONSTRAINTS;

CREATE TABLE SHOPS
(shopID VARCHAR2(10),
shopAddress VARCHAR2(35),
shopTown VARCHAR2(20),
shopPostcode NUMBER(4),
shopPhone NUMBER(10),
shopEMail VARCHAR2(35),
CONSTRAINT PK_SHOPS PRIMARY KEY (shopID));

CREATE TABLE ITEMS
(itemID VARCHAR2(10),
itemDescription VARCHAR2(35),
itemSize VARCHAR2(20),
itemColour VARCHAR2(10),
itemPrice NUMBER(5,2),
itemQuantityAvailable NUMBER(4),
CONSTRAINT PK_ITEMS PRIMARY KEY (itemID));

CREATE TABLE SUPPLIERS
(suppID VARCHAR2(10),
suppName VARCHAR2(30),
suppAddress VARCHAR2(25),
suppTown VARCHAR2(20),
suppPostcode NUMBER(4),
suppPhone NUMBER(9),
suppEMail VARCHAR2(33),
CONSTRAINT PK_SUPPLIERS PRIMARY KEY (suppID));

CREATE TABLE CUSTOMERS
(custID VARCHAR2(10),
custLName VARCHAR2(15),
custFName VARCHAR2(15),
custAddress VARCHAR2(25),
custTown VARCHAR2(20),
custPostcode NUMBER(4),
custPhone NUMBER(9),
custEmail VARCHAR2(25),
shopID VARCHAR2(10),
CONSTRAINT PK_CUSTOMERS PRIMARY KEY (custID),
CONSTRAINT fk_shopID FOREIGN KEY (shopID) 
REFERENCES SHOPS(shopID));

CREATE TABLE ORDERS
(orderNo NUMBER(10),
orderDate DATE,
dispatchDate DATE,
custID VARCHAR2(10),
CONSTRAINT PK_ORDERS PRIMARY KEY (orderNo),
CONSTRAINT fk_custID FOREIGN KEY (custID) 
REFERENCES CUSTOMERS(custID));

CREATE TABLE SHOP_ITEMS
(shopID VARCHAR2(10),
itemID VARCHAR2(10),
shopQuantity NUMBER (4),
CONSTRAINT PK_Shop_Items PRIMARY KEY (shopID, itemID),
CONSTRAINT fk_Shop_Items_shopID FOREIGN KEY (shopID) 
REFERENCES SHOPS(shopID),
CONSTRAINT fk_Shop_Items_itemID FOREIGN KEY (itemID) 
REFERENCES ITEMS(itemID));

CREATE TABLE ORDER_ITEMS
(orderNo NUMBER(10),
itemID VARCHAR2(10),
orderQuantity NUMBER (4),
CONSTRAINT PK_Order_Items PRIMARY KEY (orderNo, itemID),
CONSTRAINT fk_Order_Items_orderNo FOREIGN KEY (orderNo) 
REFERENCES ORDERS(orderNo),
CONSTRAINT fk_Order_Items_itemID FOREIGN KEY (itemID) 
REFERENCES ITEMS(itemID));

CREATE TABLE SUPPLIER_ITEMS
(suppID VARCHAR2(10),
itemID VARCHAR2(10),
suppQuantity NUMBER (4),
CONSTRAINT PK_Supplier_Items PRIMARY KEY (suppID, itemID),
CONSTRAINT fk_Supplier_Items_suppID FOREIGN KEY (suppID) 
REFERENCES SUPPLIERS(suppID),
CONSTRAINT fk_Supplier_Items_itemID FOREIGN KEY (itemID) 
REFERENCES ITEMS(itemID));

COMMIT;